name: Deploy Nginx to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the CI/CD pipeline on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Set up Docker Buildx for building multi-platform images (optional, but good practice)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Build and push Docker image to Docker Hub
    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/nginx-hello .
        docker push your-dockerhub-username/nginx-hello

    # SSH into EC2 and pull the Docker image to run it
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop any existing containers
          docker stop nginx-container || true
          docker rm nginx-container || true
          # Pull the Docker image from Docker Hub and run it
          docker pull your-dockerhub-username/nginx-hello
          docker run -d --name nginx-container -p 80:80 your-dockerhub-username/nginx-hello
