name: Deploy Nginx to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the CI/CD pipeline on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Set up Docker Buildx for building multi-platform images (optional, but good practice)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Docker image locally without pushing to a registry
    - name: Build Docker Image
      run: |
        docker build -t nginx-hello .

    # Deploy the Docker image to EC2 instance via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop and remove any existing containers
          docker stop nginx-container || true
          docker rm nginx-container || true
          # Run the new Docker image on EC2
          docker run -d --name nginx-container -p 80:80 nginx-hello
